# NumPy Basics

In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]

In [3]:
type(mylist)

list

In [4]:
np.array(mylist)

array([1, 2, 3])

In [5]:
myarr = np.array(mylist)

In [6]:
type(myarr)

numpy.ndarray

In [7]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0,10, 2)

array([0, 2, 4, 6, 8])

In [11]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [14]:
np.linspace(0,10,3) #Returns 3 evenly spaced numbers between 0 and including 10

array([ 0.,  5., 10.])

In [15]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
np.random.rand(5,2)

array([[0.13146426, 0.19240088],
       [0.89285774, 0.91702317],
       [0.67361454, 0.01543179],
       [0.61900421, 0.8526031 ],
       [0.11232043, 0.42246294]])

In [19]:
np.random.randn(10)

array([ 0.24031495, -1.27271444,  0.45195095, -0.04844881,  1.51874579,
        0.14825019,  2.12344575,  0.70749628,  0.20731716, -0.03125639])

In [20]:
np.random.randn(2,3)

array([[-0.96009652,  0.85255677, -0.0589944 ],
       [-0.39878249,  2.12867104, -0.07478384]])

In [21]:
np.random.randint(0,101,5)

array([42, 22, 12, 75, 84])

In [22]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [23]:
arr = np.arange(0,25)

In [26]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [27]:
ranarr = np.random.randint(0,101,10)

In [28]:
ranarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [29]:
ranarr.max()

99

In [30]:
ranarr.min()

2

In [31]:
ranarr.argmax(), ranarr.argmin()

(5, 7)

In [32]:
arr.shape

(25,)

In [33]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])